version: '3.7'

services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    expose:
      - 5432

  app:
    build:
      context: .

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/
    command: ["/task_manager/docker/start.sh"]
    ports:
      - "8000:8000"

    depends_on:
      - db

volumes:
  postgres_volume: