version: '3.7'

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/:rw

  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    command: ["/task_manager/docker/start.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db

volumes:
  pgdata: