# Generated by Django 4.2.3 on 2023-07-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0003_alter_status_date_of_creation'),
        ('labels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_tasks', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='executor_tasks', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(related_name='labels', to='labels.label')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='statuses.status')),
            ],
        ),
    ]
