name: main-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: | 
          pip install -r requirements.txt
          make install
#      - name: Run Tests
#        env:
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#        run: make tests
      - name: Run CodeCoverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true