# Generated by Django 4.2.3 on 2023-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, verbose_name='name')),
                ('date_of_creation', models.DateTimeField(verbose_name='date_creation')),
            ],
        ),
    ]
