# Generated by Django 4.2.3 on 2023-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, verbose_name='date_creation'),
        ),
    ]
